// Mocks generated by Mockito 5.4.6 from annotations
// in sgp_app/test/paulo/paulo_alergias_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sgp_app/features/medicamentos_alergias/domain/models/allergy_model.dart'
    as _i2;
import 'package:sgp_app/features/medicamentos_alergias/domain/repositories/allergy_repository_interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAllergyModel_0 extends _i1.SmartFake implements _i2.AllergyModel {
  _FakeAllergyModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAllergyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAllergyRepository extends _i1.Mock
    implements _i3.IAllergyRepository {
  MockIAllergyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AllergyModel> createAllergy(
    _i2.CreateAllergyRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAllergy, [request]),
            returnValue: _i4.Future<_i2.AllergyModel>.value(
              _FakeAllergyModel_0(
                this,
                Invocation.method(#createAllergy, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.AllergyModel>);

  @override
  _i4.Future<List<_i2.AllergyModel>> getAllergiesByPatient(
    String? pacienteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllergiesByPatient, [pacienteId]),
            returnValue: _i4.Future<List<_i2.AllergyModel>>.value(
              <_i2.AllergyModel>[],
            ),
          )
          as _i4.Future<List<_i2.AllergyModel>>);

  @override
  _i4.Future<_i2.AllergyModel> updateAllergyStatus({
    required String? allergyId,
    required _i2.AllergyStatus? newStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllergyStatus, [], {
              #allergyId: allergyId,
              #newStatus: newStatus,
            }),
            returnValue: _i4.Future<_i2.AllergyModel>.value(
              _FakeAllergyModel_0(
                this,
                Invocation.method(#updateAllergyStatus, [], {
                  #allergyId: allergyId,
                  #newStatus: newStatus,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AllergyModel>);

  @override
  _i4.Future<List<_i2.MedicationModel>> searchMedications(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMedications, [query]),
            returnValue: _i4.Future<List<_i2.MedicationModel>>.value(
              <_i2.MedicationModel>[],
            ),
          )
          as _i4.Future<List<_i2.MedicationModel>>);
}
