// Mocks generated by Mockito 5.4.6 from annotations
// in sgp_app/test/santiago/santiago_historial_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sgp_app/features/historial/domain/models/patient_model.dart'
    as _i2;
import 'package:sgp_app/features/historial/domain/repositories/historial_repository_interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClinicalRecordModel_0 extends _i1.SmartFake
    implements _i2.ClinicalRecordModel {
  _FakeClinicalRecordModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IHistorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHistorialRepository extends _i1.Mock
    implements _i3.IHistorialRepository {
  MockIHistorialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ClinicalRecordModel> createRecord(
    _i2.CreateClinicalRecordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRecord, [request]),
            returnValue: _i4.Future<_i2.ClinicalRecordModel>.value(
              _FakeClinicalRecordModel_0(
                this,
                Invocation.method(#createRecord, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ClinicalRecordModel>);

  @override
  _i4.Future<_i2.ClinicalRecordModel> getRecordByPatientId(
    String? pacienteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordByPatientId, [pacienteId]),
            returnValue: _i4.Future<_i2.ClinicalRecordModel>.value(
              _FakeClinicalRecordModel_0(
                this,
                Invocation.method(#getRecordByPatientId, [pacienteId]),
              ),
            ),
          )
          as _i4.Future<_i2.ClinicalRecordModel>);

  @override
  _i4.Future<_i2.ClinicalRecordModel> updateRecord({
    required String? recordId,
    required _i2.CreateClinicalRecordRequest? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecord, [], {
              #recordId: recordId,
              #data: data,
            }),
            returnValue: _i4.Future<_i2.ClinicalRecordModel>.value(
              _FakeClinicalRecordModel_0(
                this,
                Invocation.method(#updateRecord, [], {
                  #recordId: recordId,
                  #data: data,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ClinicalRecordModel>);

  @override
  _i4.Future<_i2.ClinicalRecordModel> archiveRecord(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveRecord, [recordId]),
            returnValue: _i4.Future<_i2.ClinicalRecordModel>.value(
              _FakeClinicalRecordModel_0(
                this,
                Invocation.method(#archiveRecord, [recordId]),
              ),
            ),
          )
          as _i4.Future<_i2.ClinicalRecordModel>);

  @override
  _i4.Future<List<_i2.PatientModel>> searchPatients(
    _i2.PatientSearchParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchPatients, [params]),
            returnValue: _i4.Future<List<_i2.PatientModel>>.value(
              <_i2.PatientModel>[],
            ),
          )
          as _i4.Future<List<_i2.PatientModel>>);
}
