// Mocks generated by Mockito 5.4.6 from annotations
// in sgp_app/test/samuel/samuel_auth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sgp_app/features/auth/domain/models/user_model.dart' as _i2;
import 'package:sgp_app/features/auth/domain/repositories/auth_repository_interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshResponse_2 extends _i1.SmartFake
    implements _i2.RefreshResponse {
  _FakeRefreshResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> createUser(_i2.CreateUserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [request]),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#createUser, [request])),
            ),
          )
          as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<void> resendVerificationEmail(String? correo) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, [correo]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.LoginResponse> login(_i2.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i4.Future<_i2.LoginResponse>);

  @override
  _i4.Future<_i2.LoginResponse> verifyOtp({
    required String? correo,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {#correo: correo, #otp: otp}),
            returnValue: _i4.Future<_i2.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#verifyOtp, [], {#correo: correo, #otp: otp}),
              ),
            ),
          )
          as _i4.Future<_i2.LoginResponse>);

  @override
  _i4.Future<_i2.RefreshResponse> refreshToken(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [refreshToken]),
            returnValue: _i4.Future<_i2.RefreshResponse>.value(
              _FakeRefreshResponse_2(
                this,
                Invocation.method(#refreshToken, [refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i2.RefreshResponse>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getStoredAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i2.UserModel?> getStoredUser() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredUser, []),
            returnValue: _i4.Future<_i2.UserModel?>.value(),
          )
          as _i4.Future<_i2.UserModel?>);
}
